apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: iapteca
type: Opaque
stringData:
  admin-user: admin
  admin-password: secure-admin-password-change-me
  replica-key: replica-set-key-for-authentication
