apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: iapteca
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: rs0
    net:
      bindIpAll: true
  init-replica-set.sh: |
    #!/bin/bash
    mongosh --eval 'rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongodb-0.mongodb-headless:27017" }
      ]
    })'
