apiVersion: v1
kind: Secret
metadata:
  name: product-catalog-secret
  namespace: iapteca
type: Opaque
stringData:
  MONGODB_URI: "mongodb://product-catalog-user:product-pass@mongodb:27017/iapteca?replicaSet=rs0&directConnection=true&authSource=admin"
  DB_USER: product-catalog-user
  DB_PASSWORD: product-pass
