apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-catalog-pdb
  namespace: iapteca
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: product-catalog
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-processing-pdb
  namespace: iapteca
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: order-processing
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: iapteca
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: iapteca
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongodb
