#!/bin/bash
# Quick reference commands for iapteca Kubernetes deployment

echo "═════════════════════════════════════════════════════════════"
echo "  iapteca Kubernetes Quick Reference Commands"
echo "═════════════════════════════════════════════════════════════"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

NAMESPACE="iapteca"

echo -e "${BLUE}📋 DEPLOYMENT COMMANDS${NC}"
echo ""
echo "# Dry-run validation (check without applying)"
echo "kubectl apply -f k8s/ --dry-run=client -n $NAMESPACE"
echo ""
echo "# Deploy all manifests"
echo "kubectl apply -f k8s/ -n $NAMESPACE"
echo ""
echo "# Deploy specific file"
echo "kubectl apply -f k8s/05-mongodb-deployment.yaml -n $NAMESPACE"
echo ""

echo -e "${BLUE}📊 MONITORING & STATUS${NC}"
echo ""
echo "# Watch pods (real-time status)"
echo "kubectl get pods -n $NAMESPACE -w"
echo ""
echo "# Get all resources"
echo "kubectl get all -n $NAMESPACE"
echo ""
echo "# Detailed pod status"
echo "kubectl get pods -n $NAMESPACE -o wide"
echo ""
echo "# HPA status"
echo "kubectl get hpa -n $NAMESPACE"
echo ""
echo "# Check resource usage"
echo "kubectl top nodes"
echo "kubectl top pods -n $NAMESPACE"
echo ""

echo -e "${BLUE}🔍 LOGS & DEBUGGING${NC}"
echo ""
echo "# Tail logs (real-time)"
echo "kubectl logs -n $NAMESPACE -f deployment/product-catalog"
echo "kubectl logs -n $NAMESPACE -f deployment/order-processing"
echo "kubectl logs -n $NAMESPACE -f deployment/api-gateway"
echo "kubectl logs -n $NAMESPACE -f deployment/mongodb"
echo ""
echo "# Previous pod logs (if crashed)"
echo "kubectl logs -n $NAMESPACE -f deployment/product-catalog --previous"
echo ""
echo "# Pod description (events, conditions)"
echo "kubectl describe pod <pod-name> -n $NAMESPACE"
echo ""
echo "# Get pod events"
echo "kubectl get events -n $NAMESPACE --sort-by='.lastTimestamp'"
echo ""

echo -e "${BLUE}🔌 PORT FORWARDING${NC}"
echo ""
echo "# API Gateway (port 8080 locally)"
echo "kubectl port-forward -n $NAMESPACE svc/api-gateway 8080:80"
echo ""
echo "# MongoDB (port 27017 locally)"
echo "kubectl port-forward -n $NAMESPACE svc/mongodb 27017:27017"
echo ""
echo "# Product-Catalog metrics (port 9090 locally)"
echo "kubectl port-forward -n $NAMESPACE svc/product-catalog 9090:9090"
echo ""
echo "# Order-Processing metrics (port 9090 locally)"
echo "kubectl port-forward -n $NAMESPACE svc/order-processing 9090:9090"
echo ""

echo -e "${BLUE}🌐 NETWORKING & SERVICES${NC}"
echo ""
echo "# Get services"
echo "kubectl get svc -n $NAMESPACE"
echo ""
echo "# Get service details with endpoints"
echo "kubectl get svc -n $NAMESPACE -o wide"
echo ""
echo "# Check service endpoints"
echo "kubectl get endpoints -n $NAMESPACE"
echo ""
echo "# Network policies"
echo "kubectl get networkpolicies -n $NAMESPACE"
echo ""
echo "# Ingress"
echo "kubectl get ingress -n $NAMESPACE"
echo ""

echo -e "${BLUE}🔐 SECRETS & CONFIG${NC}"
echo ""
echo "# List secrets (encoded)"
echo "kubectl get secrets -n $NAMESPACE"
echo ""
echo "# Decode specific secret"
echo "kubectl get secret mongodb-secret -n $NAMESPACE -o jsonpath='{.data.admin-password}' | base64 -d"
echo ""
echo "# List configmaps"
echo "kubectl get configmaps -n $NAMESPACE"
echo ""
echo "# View configmap content"
echo "kubectl get configmap api-gateway-config -n $NAMESPACE -o yaml"
echo ""

echo -e "${BLUE}💾 STORAGE & PERSISTENCE${NC}"
echo ""
echo "# PersistentVolumeClaims"
echo "kubectl get pvc -n $NAMESPACE"
echo ""
echo "# PersistentVolumes"
echo "kubectl get pv"
echo ""
echo "# Storage classes"
echo "kubectl get storageclass"
echo ""

echo -e "${BLUE}🏃 EXECUTE COMMANDS IN PODS${NC}"
echo ""
echo "# Execute shell in pod"
echo "kubectl exec -it -n $NAMESPACE deployment/mongodb -- sh"
echo ""
echo "# MongoDB check"
echo "kubectl exec -it -n $NAMESPACE deployment/mongodb -- mongosh --eval \"db.adminCommand('ping')\""
echo ""
echo "# Check pod environment"
echo "kubectl exec -n $NAMESPACE deployment/product-catalog -- env | grep MONGO"
echo ""

echo -e "${BLUE}⚙️  RBAC & SECURITY${NC}"
echo ""
echo "# Check service accounts"
echo "kubectl get sa -n $NAMESPACE"
echo ""
echo "# Check RBAC roles"
echo "kubectl get role -n $NAMESPACE"
echo ""
echo "# Check role bindings"
echo "kubectl get rolebinding -n $NAMESPACE"
echo ""
echo "# Check pod security"
echo "kubectl get pods -n $NAMESPACE -o jsonpath='{range .items[*]}{.metadata.name}{\"\\t\"}{.spec.securityContext}{\"\\n\"}{end}'"
echo ""

echo -e "${BLUE}🔄 UPDATES & ROLLOUTS${NC}"
echo ""
echo "# Check rollout status"
echo "kubectl rollout status deployment/product-catalog -n $NAMESPACE"
echo ""
echo "# Rollout history"
echo "kubectl rollout history deployment/product-catalog -n $NAMESPACE"
echo ""
echo "# Rollback to previous version"
echo "kubectl rollout undo deployment/product-catalog -n $NAMESPACE"
echo ""
echo "# Update image"
echo "kubectl set image deployment/product-catalog product-catalog=bouncytorch/iapteca:v2 -n $NAMESPACE"
echo ""
echo "# Restart deployment"
echo "kubectl rollout restart deployment/product-catalog -n $NAMESPACE"
echo ""

echo -e "${BLUE}🗑️  CLEANUP${NC}"
echo ""
echo "# Delete namespace (everything!)"
echo "kubectl delete namespace $NAMESPACE"
echo ""
echo "# Delete specific resource"
echo "kubectl delete deployment product-catalog -n $NAMESPACE"
echo "kubectl delete service api-gateway -n $NAMESPACE"
echo ""
echo "# Delete with cascading (wait for dependents)"
echo "kubectl delete deployment product-catalog -n $NAMESPACE --cascade=background"
echo ""

echo -e "${BLUE}🧪 TESTING${NC}"
echo ""
echo "# Test API Gateway from within cluster"
echo "kubectl exec -it -n $NAMESPACE deployment/api-gateway -- wget -O- http://localhost:8000/health"
echo ""
echo "# Test MongoDB connectivity from service"
echo "kubectl run -it --rm debug --image=mongo --restart=Never -n $NAMESPACE -- mongosh mongodb://admin:secure-admin-password-change-me@mongodb:27017"
echo ""
echo "# Test DNS resolution"
echo "kubectl exec -it -n $NAMESPACE deployment/api-gateway -- nslookup mongodb"
echo ""

echo -e "${BLUE}📱 MINIKUBE SPECIFIC${NC}"
echo ""
echo "# Start Minikube"
echo "minikube start --cpus=4 --memory=6144"
echo ""
echo "# Check status"
echo "minikube status"
echo ""
echo "# Enable addons"
echo "minikube addons enable ingress"
echo "minikube addons enable metrics-server"
echo ""
echo "# Open service in browser"
echo "minikube service api-gateway -n $NAMESPACE"
echo ""
echo "# Get Minikube IP"
echo "minikube ip"
echo ""
echo "# SSH into Minikube"
echo "minikube ssh"
echo ""
echo "# Stop Minikube"
echo "minikube stop"
echo ""
echo "# Delete Minikube"
echo "minikube delete"
echo ""

echo -e "${BLUE}🛠️  USEFUL ALIASES${NC}"
echo ""
echo "# Add to ~/.bashrc or ~/.zshrc"
echo "alias k='kubectl'"
echo "alias kn='kubectl -n iapteca'"
echo "alias kgp='kubectl get pods -n iapteca'"
echo "alias kd='kubectl describe'"
echo "alias kl='kubectl logs -f'"
echo ""

echo -e "${GREEN}═════════════════════════════════════════════════════════════${NC}"
echo "For more info, see README.md and ARCHITECTURE.md"
echo ""
